version: '{build}'
configuration:
    - release
os: Visual Studio 2015
before_build:
    - git submodule update --init --recursive
    - git clone -q https://github.com/prismskylabs/prismprotobuf.git C:\projects\prismprotobuf
    - set PROTOBUF_INCLUDE_DIRS=C:\projects\prismprotobuf\install\win32\include
    - set PROTOBUF_LIBRARIES=C:\projects\prismprotobuf\install\win32\lib
    - set PROTOBUF_FOUND=true
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
build:
    project: C:\projects\protoqueue\build\protoqueue.sln
test_script:
    - cd C:\projects\protoqueue\build
    - ctest -VV -C %Configuration%
