version: '{build}'
configuration:
    - release
os: Visual Studio 2015
before_build:
    - git submodule update --init --recursive
    - set PROTOBUF_INCLUDE_DIRS=test_value
    - set PROTOBUF_LIBRARIES=test_library_value
    - set PROTOBUF_FOUND=true
    - set PROTOBUF_INCLUDE_DIR=test_value
    - set PROTOBUF_LIBRARY=test_library_value
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
build:
    project: C:\projects\protoqueue\build\protoqueue.sln
test_script:
    - cd C:\projects\protoqueue\build
    - ctest -VV -C %Configuration%
